services:
  postgis:
    build:
      context: ..
      dockerfile: docker/postgis/Dockerfile
    image: 'prge_mwi_postgis'
    container_name: 'prge_mwi_postgis'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5444:5432
    volumes:
      - postgis-prge-mwi-data:/var/lib/postgresql/data

volumes:
  postgis-prge-mwi-data: