x-enviroment:
  #DB
  - &env-postgres-db POSTGRES_DB=${POSTGRES_DB}
  - &env-postgres-user POSTGRES_USER=${POSTGRES_USER}
  - &env-postgres-password POSTGRES_PASSWORD=${POSTGRES_PASSWORD}




services:
  postgis:
    build:
      context: ..
      dockerfile: docker/postgis/Dockerfile
    image: 'prge_mwi_postgis'
    container_name: prge-mwi-postgis-${ENV_NAME}
    environment:
      - *env-postgres-db
      - *env-postgres-user
      - *env-postgres-password
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgis-prge-mwi-data:/var/lib/postgresql/data

  geoserver:
    build:
      context: ..
      dockerfile: docker/geoserver/Dockerfile
    image: 'prge_mwi_geoserver'
    container_name: prge-mwi-geoserver-${ENV_NAME}
    ports:
      - ${GEOSERVER_PORT}:8080
    volumes:
      - ../.tmp/data-${ENV_NAME}:/opt/geoserver_data



volumes:
  postgis-prge-mwi-data: