name: build and push and deploy

on:
  push:
    branches:
      - env-test

permissions:
  contents: read
  packages: write


jobs:
  build-and-push:
    name: Build & Push
    runs-on:
      - self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Print
        run: echo 'witaj'
#
#      - name: Login to GHCR
#        uses: docker/login-action@v2
#        with:
#          registry: ghcr.io
#          username: ${{github.actor}}
#          password: ${{secrets.GITHUB_TOKEN}}
#
#
#      - name: set up build
#        run: |
#          docker buildx build \
#          -t ghcr.io/${{github.repository_owner}}